Fixed example code
The original code have errors, maybe due to an older version of Docopt:
```
$ runhaskell test.hs 

test.hs:19:15:
    Not in scope: ‘getArgOrDieWith’
    Perhaps you meant one of these:
      ‘getArgOrExitWith’ (imported from System.Console.Docopt),
      ‘getArgOrDie’ (line 19)

test.hs:22:11:
    Not in scope: ‘parseArgsOrDie’
    Perhaps you meant ‘parseArgsOrExit’ (imported from System.Console.Docopt)

test.hs:25:18:
    Not in scope: ‘getArgOrDieWith’
    Perhaps you meant one of these:
      ‘getArgOrExitWith’ (imported from System.Console.Docopt),
      ‘getArgOrDie’ (line 19)

test.hs:32:20:
    Not in scope: ‘getArgOrDieWith’
    Perhaps you meant one of these:
      ‘getArgOrExitWith’ (imported from System.Console.Docopt),
      ‘getArgOrDie’ (line 19)
```